version: '3.3'

services:

  backend:
    image: "project-planner/backend:${DeployEnv}-${DeployVersion}"
    ports:
      - "${DeployBackendPort}:3000"

  frontend:
    image: "project-planner/frontend:${DeployEnv}-${DeployVersion}"
    ports:
      - "${DeployFrontendPort}:8080"