version: "3"
services:
  backend:
    build:
      context: ./back-end
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./front-end
    ports:
      - "8080:8080"
    depends_on:
      - backend
